name : Deploy to railway

on: 
 push:
   branches: [master]

jobs: 
 deploy:
  runs-on: ubuntu-latest

  steps: 
  - name : Echo the branch name
    run : echo "current branch - ${{github.ref_name}}"
