name : Deploy to railway

on: 
 push:
   branches: "v[0-9]+.[0-9]+" 

jobs: 
 deploy:
  runs-on: ubuntu-latest

  steps: 
  - name : Echo the branch name
    run : echo "current branch - ${{github.ref_name}}"

  - name : Action checkout 
    uses : actions/checkout@v3
  
  - name : Try using Node 16
    use : actions/setup-node@v1
     with : 
        node-version: 16
    
  - name: Installing Railway
    run: npm i -g @railway/cli

  - name: Deploy
    run: railway up
    env:
     RAILWAY_TOKEN: ${{secrets.fortune_token}}
    
