name : Deploy to railway

on: 
 push:
   branches: "v[0-9]+.[0-9]+" 

jobs: 
 deploy:
  runs-on: ubuntu-latest

  steps: 
  - name : Echo the branch name
    run : echo "current branch - ${{github.ref_name}}"

  - name : Action checkout 
    uses : actions/checkout@v3
  
  - name : Try using Node 16
    uses : actions/setup-node@v1
    with : 
        node-version: 16
    
  - name: Installing Railway
    run: npm i -g @railway/cli

  - name: Deploy
    run: railway up
    env:
      RAILWAY_TOKEN: ${{secrets.FORTUNE_TOKEN}}
    
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.23.0
  with:
    # Slack channel id, channel name, or user id to post message.
    # See also: https://api.slack.com/methods/chat.postMessage#channels
    channel-id: 'CHANNEL_ID'
    # For posting a rich message using Block Kit
    payload: |
{
	"blocks": [
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": "DipSA55 CI/CD Assignment Submission",
				"emoji": true
			}
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "*Name:*\nKhant Zaw Hein"
				},
				{
					"type": "mrkdwn",
					"text": "*Metriculation:*\nA0265074A"
				}
			]
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "*Email:*\ne105749@u.nus.edu"
				},
				{
					"type": "mrkdwn",
					"text": "*Repository:*\nhttps://github.com/Khant-Zaw-Hein/goFortune"
				}
			]
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "*Deployment:*\nhttps://serene-shock-production.up.railway.app/"
				}
			]
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "<https://serene-shock-production.up.railway.app/|Open Application>"
				}
			]
		}
	]
}

  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}