name : Deploy to Railway

# assignment 1)
on: 
 push:
   branches: "v[0-9]+.[0-9]+" 

jobs: 
 deploy:
  runs-on: ubuntu-latest
  # assignment 5)
  if: "!contains(github.event.head_commit.message, '#NORUN')"

  steps: 
  - name : Echo the branch name
    run : echo "current branch - ${{github.ref_name}}"

#assignment 2)
  - name : Action checkout 
    uses : actions/checkout@v3
  
  - name : Try using Node 16
    uses : actions/setup-node@v1
    with : 
        node-version: 16
    
  - name: Installing Railway
    run: npm i -g @railway/cli

  - name: Deploy to railway
    run: railway up
    env:
      RAILWAY_TOKEN: ${{secrets.FORTUNE_TOKEN}}

# assignment 3)
  - name: Release 
    uses: actions/create-release@v1
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with: 
      # tag_name: ${{github.ref}}
      # release_name: ${{github.ref}}
      tag_name: ${{github.ref_name}}
      release_name: ${{github.ref_name}}
      body: |
        Changes in this Release
        - First Change
        - Second Change
      draft: false
      prerelease: false

# assignment 4)
  - name: Send custom JSON data to Slack workflow
    id: slack
    uses: slackapi/slack-github-action@v1.23.0
    with:
    # For posting a rich message using Block Kit
     payload: |
      {
      "blocks": [
        {
       "type": "header",
       "text": {
       "type": "plain_text",
       "text": "DipSA55 CI/CD Assignment Submission",
       "emoji": true
       }
       },
       {
       "type": "section",
       "fields": [
       {
       "type": "mrkdwn",
        "text": "*Name:*\nKhant Zaw Hein"
       },
       {
       "type": "mrkdwn",
       "text": "*Metriculation:*\nA0265074A"
       }
       ]
       },
      {
      "type": "section",
      "fields": [
      {
      "type": "mrkdwn",
      "text": "*Email:*\ne105749@u.nus.edu"
      },
      {
      "type": "mrkdwn",
      "text": "*Repository:*\nhttps://github.com/Khant-Zaw-Hein/goFortune"
      }
      ]
      },
      {
      "type": "section",
      "fields": [
      {
      "type": "mrkdwn",
      "text": "*Deployment:*\nhttps://serene-shock-production.up.railway.app/"
      }
      ]
      },
      {
      "type": "section",
      "fields": [
      {
      "type": "mrkdwn",
      "text": "<https://serene-shock-production.up.railway.app/|Open Application>"
      }
      ]
      }
      ]
      }

  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_SUBMIT_URL}}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

#assignment 5) 

#    variables:
#    COMMIT_MESSAGE: "#NORUN"

# workflow:
#   rules:
#     - if: $CI_COMMIT_MESSAGE =~ /^.*COMMIT_MESSAGE/
#       when: never
#     - when: always
