name : Deploy to railway

on: 
 push:
   branches:  "v[0-9].[0-9]" 

jobs: 
 deploy:
  runs-on: ubuntu-latest

  steps: 
  - name : Echo the branch name
    run : echo "current branch - ${{github.ref_name}}"
